<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Connector.Upgrade.Core\Connector.Upgrade.Core.csproj" />
    <ProjectReference Include="..\Connector.Upgrade.WindowsMsi\Connector.Upgrade.WindowsMsi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\infra\netbird\v0.79.0-windows-x64.lock.json"
                      Link="v0.79.0-windows-x64.lock.json" />
  </ItemGroup>

</Project>
