<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Connector.Upgrade.Core\Connector.Upgrade.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Connector.Upgrade.WindowsJournal.Tests" />
    <InternalsVisibleTo Include="Connector.Upgrade.MachineJournal" />
    <InternalsVisibleTo Include="Connector.Upgrade.MachineJournal.Tests" />
  </ItemGroup>
</Project>
