<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Connector.Access.NetBird</PackageId>
    <Version>0.2.7</Version>
    <Authors>Structura</Authors>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Connector.Access\Connector.Access.csproj" />
    <ProjectReference Include="..\Connector.Access.Contracts\Connector.Access.Contracts.csproj" />
  </ItemGroup>
</Project>
