<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Connector.Upgrade.MutualMachineChannel\Connector.Upgrade.MutualMachineChannel.csproj" />
    <ProjectReference Include="..\Connector.Upgrade.MachineIpc\Connector.Upgrade.MachineIpc.csproj" />
    <ProjectReference Include="..\Connector.Upgrade.MachineDispatcher\Connector.Upgrade.MachineDispatcher.csproj" />
  </ItemGroup>
</Project>
